// This file is auto-generated by @ts-sdk-gen/openapi-ts

export type PostFooData = {
    body?: never;
    url: '/foo';
};

export type PostFooResponses = {
    /**
     * OK
     */
    200: string;
    /**
     * Created
     */
    204: void;
};

export type PostFooResponse = PostFooResponses[keyof PostFooResponses];