// This file is auto-generated by @ts-sdk-gen/openapi-ts

export type PostFooData = {
    body?: never;
    path?: never;
    query?: {
        foo?: Array<string>;
    };
    url: '/foo';
};

export type PostFooResponses = {
    /**
     * OK
     */
    default: unknown;
};