// This file is auto-generated by @ts-sdk-gen/openapi-ts

export type Foo = {
    status?: number;
};

export type PostV1FooData = {
    body: {
        file: (Blob | File);
        info: string;
    };
};

export type PostV1FooResponse = (Foo);

export type PostV1FooError = unknown;