// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@ts-sdk-gen/client-fetch';
import type { PostFooData } from './types.gen';

export const client = createClient(createConfig());

export const postFoo = <ThrowOnError extends boolean = false>(options?: Options<PostFooData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
        ...options,
        url: '/foo',
        querySerializer: {
            array: {
                explode: false,
                style: 'form'
            }
        }
    });
};