// This file is auto-generated by @ts-sdk-gen/openapi-ts

/**
 * Foo
 */
export type Foo = {
    page?: number;
};

export type PostFooData = {
    /**
     * Foo
     */
    body: Foo;
    url: '/foo';
};

export type PostFooResponses = {
    /**
     * OK
     */
    200: unknown;
};