// This file is auto-generated by @ts-sdk-gen/openapi-ts

export type Type = 'foo' | 'bar';

export const Type = {
    FOO: 'foo',
    BAR: 'bar'
} as const;

export type Foo = {
    type?: 'foo' | 'bar';
};