// This file is auto-generated by @ts-sdk-gen/openapi-ts

export type Foo = {
    foo: string;
};

export type Bar = Foo & {
    [key: string]: never;
};

export type Baz = Foo & {
    bar: string;
};