// This file is auto-generated by @ts-sdk-gen/openapi-ts

export enum _110 {
    '1_10' = '1-10',
    '11_20' = '11-20'
}

export enum MyFoo {
    my_foo = 'myFoo',
    my_bar = 'myBar'
}

export enum MyFoo2 {
    my_foo = 'MyFoo',
    my_bar = 'MyBar'
}

export type Foo = 'foo' | 'bar' | null | '' | true | false;

export enum Numbers {
    _100 = 100,
    _200 = 200,
    _300 = 300
}