name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}=${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build, Lint, Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.7

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Run linter
        run: pnpm lint

      - name: Run type check
        run: pnpm typecheck

      - name: Run unit tests
        run: pnpm test

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Publish previews
        if: matrix.node-version == '21.x' && matrix.os == 'ubuntu-latest'
        run: pnpx pkg-pr-new publish --compact --pnpm './packages/*'
